In [1]:
from sklearn import metrics
import xgboost
from xgboost import XGBRegressor
#!pip install catboost
#import catboost
#from catboost import CatBoostRegressor
#!pip install lightgbm
#import lightgbm
#from lightgbm import LGBMRegressor
from sklearn.ensemble import RandomForestRegressor
import numpy as np
!pip install h2o
import h2o
from h2o.automl import H2OAutoML
h2o.init(
    nthreads=-1,     # number of threads when launching a new H2O server
    max_mem_size=12  # in gigabytes
)
!pip install pytorch-tabnet
from pytorch_tabnet.tab_model import TabNetRegressor

import torch

Requirement already satisfied: h2o in /usr/local/lib/python3.7/dist-packages (3.32.1.3)
Requirement already satisfied: tabulate in /usr/local/lib/python3.7/dist-packages (from h2o) (0.8.9)
Requirement already satisfied: colorama>=0.3.8 in /usr/local/lib/python3.7/dist-packages (from h2o) (0.4.4)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from h2o) (2.23.0)
Requirement already satisfied: future in /usr/local/lib/python3.7/dist-packages (from h2o) (0.16.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->h2o) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->h2o) (2020.12.5)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->h2o) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->h2o) (2.10)
Checking whether there is an H2O instance running at http://localhost:54321 ..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "11.0.11" 2021-04-20; OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04); OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.7/dist-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmp28x2r0ks
  JVM stdout: /tmp/tmp28x2r0ks/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmp28x2r0ks/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  ------------------------------------------------------------------
H2O_cluster_uptime:         02 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.32.1.3
H2O_cluster_version_age:    24 days
H2O_cluster_name:           H2O_from_python_unknownUser_5cdien
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    12 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         accepting new members, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
H2O_API_Extensions:         Amazon S3, XGBoost, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python_version:             3.7.10 final
--------------------------  ------------------------------------------------------------------

Requirement already satisfied: pytorch-tabnet in /usr/local/lib/python3.7/dist-packages (3.1.1)
Requirement already satisfied: tqdm<5.0,>=4.36 in /usr/local/lib/python3.7/dist-packages (from pytorch-tabnet) (4.41.1)
Requirement already satisfied: torch<2.0,>=1.2 in /usr/local/lib/python3.7/dist-packages (from pytorch-tabnet) (1.8.1+cu101)
Requirement already satisfied: numpy<2.0,>=1.17 in /usr/local/lib/python3.7/dist-packages (from pytorch-tabnet) (1.19.5)
Requirement already satisfied: scikit_learn>0.21 in /usr/local/lib/python3.7/dist-packages (from pytorch-tabnet) (0.24.2)
Requirement already satisfied: scipy>1.4 in /usr/local/lib/python3.7/dist-packages (from pytorch-tabnet) (1.4.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from torch<2.0,>=1.2->pytorch-tabnet) (3.7.4.3)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit_learn>0.21->pytorch-tabnet) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit_learn>0.21->pytorch-tabnet) (2.1.0)

## AutoML

In [9]:
train = h2o.import_file('/content/syn_sages.csv')

import time
import itertools
from h2o.estimators.gbm import H2OGradientBoostingEstimator
from h2o.grid.grid_search import H2OGridSearch

Parse progress: |█████████████████████████████████████████████████████████| 100%

In [60]:
train_, valid = train.split_frame(ratios = [.85])
for cols in ['Dip', 'Slice', 'Block', 'SAGES']:
  train_[cols] = train_[cols].asfactor()
  valid[cols] = valid[cols].asfactor()

X = train_.drop(['Withdrawal load rise', "Slice"], axis=1)

gbm = H2OGradientBoostingEstimator(ntrees = 1000,
    stopping_metric = "rmse",
    nfolds=6)

gbm.train(x=X.columns, y="Withdrawal load rise", training_frame=train_, validation_frame=valid)

print(gbm)

/usr/local/lib/python3.7/dist-packages/h2o/estimators/estimator_base.py:200: RuntimeWarning: Stopping metric is ignored for _stopping_rounds=0.
  warnings.warn(mesg["message"], RuntimeWarning)

gbm Model Build progress: |███████████████████████████████████████████████| 100%
Model Details
=============
H2OGradientBoostingEstimator :  Gradient Boosting Machine
Model Key:  GBM_model_python_1623519704518_12


Model Summary:

     number_of_trees  ...  max_leaves  mean_leaves
0             1000.0  ...         5.0        3.958

[1 rows x 10 columns]

ModelMetricsRegression: gbm
** Reported on train data. **

MSE: 0.0017161615279630996
RMSE: 0.04142657996942421
MAE: 0.03211167279411765
RMSLE: 0.00033452727346971323
Mean Residual Deviance: 0.0017161615279630996

ModelMetricsRegression: gbm
** Reported on validation data. **

MSE: 1101.8332544407333
RMSE: 33.19387374864123
MAE: 27.091041905750807
RMSLE: 0.29226721763113445
Mean Residual Deviance: 1101.8332544407333

ModelMetricsRegression: gbm
** Reported on cross-validation data. **

MSE: 1716.9801251643614
RMSE: 41.43645888784853
MAE: 33.29561506998827
RMSLE: 0.342551292345115
Mean Residual Deviance: 1716.9801251643614

Cross-Validation Metrics Summary:

                                  mean  ...  cv_5_valid  cv_6_valid
0                     mae     33.00777  ...   34.824577   25.893402
1  mean_residual_deviance    1668.6664  ...   2094.1174   841.64325
2                     mse    1668.6664  ...   2094.1174   841.64325
3                      r2  -0.92653555  ...  -2.4396894   0.4576986
4       residual_deviance    1668.6664  ...   2094.1174   841.64325
5                    rmse    40.386333  ...   45.761528    29.01109
6                   rmsle   0.32168743  ...  0.39739627  0.19783428

[7 rows x 9 columns]

Scoring History:

                timestamp  ... validation_mae  validation_deviance
0     2021-06-12 18:30:42  ...      17.133690           539.961623
1     2021-06-12 18:30:42  ...      16.147438           513.409885
2     2021-06-12 18:30:42  ...      15.472688           501.918149
3     2021-06-12 18:30:42  ...      15.605192           514.521390
4     2021-06-12 18:30:42  ...      15.691490           508.423847
5     2021-06-12 18:30:42  ...      15.984728           511.280779
6     2021-06-12 18:30:42  ...      16.451477           516.332600
7     2021-06-12 18:30:42  ...      17.180240           528.684305
8     2021-06-12 18:30:42  ...      17.373432           529.709848
9     2021-06-12 18:30:42  ...      18.053498           534.237283
10    2021-06-12 18:30:42  ...      18.557871           546.883089
11    2021-06-12 18:30:42  ...      19.085530           560.062263
12    2021-06-12 18:30:42  ...      19.847147           596.395852
13    2021-06-12 18:30:42  ...      19.819680           590.481857
14    2021-06-12 18:30:42  ...      20.249002           606.301857
15    2021-06-12 18:30:42  ...      20.552688           621.487846
16    2021-06-12 18:30:42  ...      20.813870           624.115130
17    2021-06-12 18:30:42  ...      21.567110           658.456294
18    2021-06-12 18:30:42  ...      21.849177           658.547015
19    2021-06-12 18:30:42  ...      22.458890           691.202438

[20 rows x 10 columns]

See the whole table with table.as_data_frame()

Variable Importances:

                 variable  relative_importance  scaled_importance  percentage
0     Withdrawal load dip         69480.867188           1.000000    0.225505
1            Conv rise mm         44311.539062           0.637752    0.143816
2                Set date         38532.164062           0.554572    0.125059
3                  Face m         26622.474609           0.383163    0.086405
4                     Dip         25117.955078           0.361509    0.081522
5               Rise load         20597.224609           0.296445    0.066850
6     withdrawal time min         19598.460938           0.282070    0.063608
7                Dip load         17053.759766           0.245445    0.055349
8           Roof exposure         15694.945312           0.225889    0.050939
9             Conv dip mm         10294.395508           0.148162    0.033411
10  Slice extraction days          9688.112305           0.139436    0.031443
11          Withdraw date          5813.193359           0.083666    0.018867
12         Blasting holes          4844.600098           0.069726    0.015723
13                  Level           430.280548           0.006193    0.001397
14                  SAGES            32.232307           0.000464    0.000105
15                  Block             0.000000           0.000000    0.000000

In [42]:
from h2o.estimators.glm import H2OGeneralizedLinearEstimator

interaction_pairs = [("Dip load", "Rise load"),
                    ("Withdrawal load dip", "Withdrawal load rise"),
                     ("Conv rise mm", "Conv dip mm")]

glm2 = H2OGeneralizedLinearEstimator(nfolds=5,
                                    alpha=0.25,
                                    interaction_pairs=interaction_pairs,
                                    keep_cross_validation_models=True,
                                    stopping_metric='rmse',
                                    family='poisson',
                                    seed=1
                                    )

X = train_.drop(['Withdrawal load rise'], axis=1)

glm2.train(x = X.columns, y = 'Withdrawal load rise', training_frame = train_, validation_frame = valid)

print(glm2)

/usr/local/lib/python3.7/dist-packages/h2o/estimators/estimator_base.py:200: RuntimeWarning: Stopping metric is ignored for _stopping_rounds=0.
  warnings.warn(mesg["message"], RuntimeWarning)

glm Model Build progress: |███████████████████████████████████████████████| 100%
Model Details
=============
H2OGeneralizedLinearEstimator :  Generalized Linear Modeling
Model Key:  GLM_model_python_1623519704518_9


GLM Model: summary

      family  ... number_of_iterations  training_frame
0    poisson  ...                    2  py_51_sid_ae98

[1 rows x 8 columns]

ModelMetricsRegressionGLM: glm
** Reported on train data. **

MSE: 256.3436398396377
RMSE: 16.010735143635277
MAE: 12.981024517984713
RMSLE: 0.13420523166915632
R^2: 0.736329724458286
Mean Residual Deviance: 2.092387561323033
Null degrees of freedom: 52
Residual degrees of freedom: 48
Null deviance: 396.5401663642061
Residual deviance: 110.89654075012074
AIC: 475.0577780952768

ModelMetricsRegressionGLM: glm
** Reported on validation data. **

MSE: 637.6079796994983
RMSE: 25.250900572048877
MAE: 23.103668318242175
RMSLE: 0.2270367846085238
R^2: 0.47285763206912723
Mean Residual Deviance: 5.466815625920341
Null degrees of freedom: 8
Residual degrees of freedom: 4
Null deviance: 106.71356106491692
Residual deviance: 49.20134063328307
AIC: 118.12207011755012

Scoring History:

               timestamp  ... validation_mae  validation_r2
0    2021-06-12 18:21:26  ...
1    2021-06-12 18:21:26  ...
2    2021-06-12 18:21:26  ...        23.1037       0.472858

[3 rows x 14 columns]

Variable Importances:

                                    variable  ...  percentage
0   Withdrawal load dip_Withdrawal load rise  ...    0.750426
1                               Conv rise mm  ...    0.137273
2                        Withdrawal load dip  ...    0.061293
3                        withdrawal time min  ...    0.051008
4                                   Slice.46  ...    0.000000
5                                   Slice.47  ...    0.000000
6                                   Slice.48  ...    0.000000
7                                   Slice.49  ...    0.000000
8                                   Slice.50  ...    0.000000
9                                   Slice.51  ...    0.000000
10                                  Slice.52  ...    0.000000
11                                  Slice.53  ...    0.000000
12                                  Slice.54  ...    0.000000
13                                  Slice.55  ...    0.000000
14                                  Slice.56  ...    0.000000
15                                  Slice.57  ...    0.000000
16                                  Slice.58  ...    0.000000
17                                  Slice.59  ...    0.000000
18                                  Slice.60  ...    0.000000
19                                  Slice.61  ...    0.000000

[20 rows x 4 columns]

See the whole table with table.as_data_frame()

In [62]:
rf = SVR()
x = sage[[col for col in sage.columns if col not in ['Withdrawal load rise', 'Set date', 'Withdraw date', 'Set']]]
y = sage['Withdrawal load rise']
#xt, xtt, yt, ytt = train_test_split(x, y, test_size=0.15)
rf.fit(xt, yt)
print('rmse', np.sqrt(metrics.mean_squared_error(ytt, rf.predict(xtt))))

rmse 22.396533209399138

In [3]:
!pip install table-evaluator

Requirement already satisfied: table-evaluator in /usr/local/lib/python3.7/dist-packages (1.2.2.post1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from table-evaluator) (4.41.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.7/dist-packages (from table-evaluator) (5.4.8)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from table-evaluator) (1.19.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from table-evaluator) (1.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from table-evaluator) (1.1.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (from table-evaluator) (0.24.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from table-evaluator) (3.2.2)
Requirement already satisfied: dython==0.5.1 in /usr/local/lib/python3.7/dist-packages (from table-evaluator) (0.5.1)
Requirement already satisfied: seaborn in /usr/local/lib/python3.7/dist-packages (from table-evaluator) (0.11.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas->table-evaluator) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->table-evaluator) (2.8.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->table-evaluator) (2.1.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->table-evaluator) (1.0.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->table-evaluator) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->table-evaluator) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->table-evaluator) (1.3.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->table-evaluator) (1.15.0)

In [4]:
!pip install ctgan

Requirement already satisfied: ctgan in /usr/local/lib/python3.7/dist-packages (0.4.2)
Requirement already satisfied: rdt<0.5,>=0.4.1 in /usr/local/lib/python3.7/dist-packages (from ctgan) (0.4.2)
Requirement already satisfied: numpy<2,>=1.18.0 in /usr/local/lib/python3.7/dist-packages (from ctgan) (1.19.5)
Requirement already satisfied: torch<2,>=1.4 in /usr/local/lib/python3.7/dist-packages (from ctgan) (1.8.1+cu101)
Requirement already satisfied: torchvision<1,>=0.5.0 in /usr/local/lib/python3.7/dist-packages (from ctgan) (0.9.1+cu101)
Requirement already satisfied: scikit-learn<1,>=0.23 in /usr/local/lib/python3.7/dist-packages (from ctgan) (0.24.2)
Requirement already satisfied: pandas<1.1.5,>=1.1 in /usr/local/lib/python3.7/dist-packages (from ctgan) (1.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from ctgan) (20.9)
Requirement already satisfied: scipy<2,>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from rdt<0.5,>=0.4.1->ctgan) (1.4.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from torch<2,>=1.4->ctgan) (3.7.4.3)
Requirement already satisfied: pillow>=4.1.1 in /usr/local/lib/python3.7/dist-packages (from torchvision<1,>=0.5.0->ctgan) (7.1.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn<1,>=0.23->ctgan) (2.1.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn<1,>=0.23->ctgan) (1.0.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas<1.1.5,>=1.1->ctgan) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas<1.1.5,>=1.1->ctgan) (2.8.1)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->ctgan) (2.4.7)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas<1.1.5,>=1.1->ctgan) (1.15.0)

In [5]:
import pandas as pd
sage = pd.read_csv('/content/sages.csv')

In [6]:
from ctgan import CTGANSynthesizer

# Identifies all the discrete columns

discrete_columns = [col for col in sage.columns]

# Initiates the CTGANSynthesizer and call its fit method to pass in the table
 
ctgan = CTGANSynthesizer(epochs=10)
ctgan.fit(sage, discrete_columns)

In [7]:
synthetic_data = ctgan.sample(1000)

In [11]:
synthetic_data.head()

   Level  Dip  Slice  Face m  ... Roof exposure  Blasting holes  Block SAGES
0   28.0    5     59     427  ...           910               0     -1    -1
1   28.5    6     67     399  ...          1840              31      1     1
2   31.0    9     51     447  ...          1530               7     -1     1
3   31.0    9     64     561  ...          1720              18     -1     1
4   31.0   11     52     549  ...          1730              25      1    -1

[5 rows x 18 columns]

In [12]:
synthetic_data.shape

(500, 18)

In [8]:
synthetic_data.to_csv('/content/syn_sages.csv', index=False)

In [14]:
sage.columns

Index(['Level', 'Dip', 'Slice', 'Face m', 'Set date', 'Dip load', 'Rise load',
       'Withdraw date', 'Withdrawal load dip', 'Withdrawal load rise',
       'Conv dip mm', 'Conv rise mm', 'Slice extraction days',
       'withdrawal time min', 'Roof exposure', 'Blasting holes', 'Block',
       'SAGES'],
      dtype='object')

In [19]:
train[541:545, :]

Level,Dip,Slice,Face m,Set date,Dip load,Rise load,Withdraw date,Withdrawal load dip,Withdrawal load rise,Conv dip mm,Conv rise mm,Slice extraction days,withdrawal time min,Roof exposure,Blasting holes,Block,SAGES
28,5,59,381,2017-06-11 00:00:00,134,35,2017-11-21 00:00:00,92,156,14,3,8,22,810,5,1,1
28.5,9,66,339,2017-09-29 00:00:00,70,131,2017-11-20 00:00:00,173,156,8,6,1,9,1110,22,1,-1
31,5,54,459,2017-08-30 00:00:00,94,70,2018-02-07 00:00:00,129,136,0,1,6,10,2350,27,1,-1
28.5,9,58,435,2017-08-12 00:00:00,98,111,2017-12-14 00:00:00,181,96,4,8,9,147,1230,7,-1,1

In [22]:
from h2o.estimators.glm import H2OGeneralizedLinearEstimator
train_, valid = train.split_frame(ratios = [.85])
for cols in ['Dip', 'Slice', 'Block', 'SAGES']:
  train_[cols] = train_[cols].asfactor()
  valid[cols] = valid[cols].asfactor()
interaction_pairs = [("Dip load", "Rise load"),
                    ("Withdrawal load dip", "Withdrawal load rise"),
                     ("Conv rise mm", "Conv dip mm"),
                      ('Dip load', 'Rise load')]

glm2 = H2OGeneralizedLinearEstimator(nfolds=5,
                                    alpha=0,
                                    interaction_pairs=interaction_pairs,
                                    keep_cross_validation_models=True,
                                    stopping_metric='rmse',
                                    family='poisson',
                                    seed=12
                                    )

X = train_.drop(['Withdrawal load rise'], axis=1)

glm2.train(x = X.columns, y = 'Withdrawal load rise', training_frame = train_, validation_frame = valid)

print(glm2)

/usr/local/lib/python3.7/dist-packages/h2o/estimators/estimator_base.py:200: RuntimeWarning: Stopping metric is ignored for _stopping_rounds=0.
  warnings.warn(mesg["message"], RuntimeWarning)

glm Model Build progress: |███████████████████████████████████████████████| 100%
Model Details
=============
H2OGeneralizedLinearEstimator :  Generalized Linear Modeling
Model Key:  GLM_model_python_1623533504698_8


GLM Model: summary

      family  ... number_of_iterations  training_frame
0    poisson  ...                    4  py_85_sid_8c15

[1 rows x 8 columns]

ModelMetricsRegressionGLM: glm
** Reported on train data. **

MSE: 109.57756870050638
RMSE: 10.467930487947767
MAE: 7.167223643069243
RMSLE: 0.08132699525426647
R^2: 0.8990879763669275
Mean Residual Deviance: 0.7803981066058896
Null degrees of freedom: 854
Residual degrees of freedom: 804
Null deviance: 7178.38205331529
Residual deviance: 667.2403811480356
AIC: 6484.708658369526

ModelMetricsRegressionGLM: glm
** Reported on validation data. **

MSE: 106.59212673835985
RMSE: 10.324346310462461
MAE: 6.998780806507256
RMSLE: 0.0685679500200198
R^2: 0.8987616188733389
Mean Residual Deviance: 0.6673928078314353
Null degrees of freedom: 144
Residual degrees of freedom: 94
Null deviance: 1150.5972796456144
Residual deviance: 96.77195713555811
AIC: 1169.0882675664807

ModelMetricsRegressionGLM: glm
** Reported on cross-validation data. **

MSE: 140.0075055826319
RMSE: 11.832476730703167
MAE: 7.725202349983816
RMSLE: 0.08734237344741004
R^2: 0.8710644808083171
Mean Residual Deviance: 0.9369740204644753
Null degrees of freedom: 854
Residual degrees of freedom: 804
Null deviance: 7181.877132815991
Residual deviance: 801.1127874971264
AIC: 6618.581064718617

Cross-Validation Metrics Summary:

                                 mean  ...  cv_4_valid  cv_5_valid
0                     mae   7.7292833  ...   7.3469515    8.520712
1  mean_residual_deviance  0.93758315  ...   0.8143546   1.0574633
2                     mse   139.49443  ...    99.26135   160.02519
3           null_deviance   1436.3754  ...   1480.1929   1512.8795
4                      r2   0.8728237  ...   0.9078871    0.862864
5       residual_deviance   160.22256  ...   144.14076   175.53891
6                    rmse   11.649625  ...    9.962999   12.650106
7                   rmsle  0.08717615  ...  0.08612597  0.09167065

[8 rows x 8 columns]

Scoring History:

               timestamp  ... validation_mae  validation_r2
0    2021-06-12 21:41:09  ...
1    2021-06-12 21:41:09  ...
2    2021-06-12 21:41:09  ...
3    2021-06-12 21:41:09  ...
4    2021-06-12 21:41:09  ...        6.99878       0.898762

[5 rows x 14 columns]

Variable Importances:

                                    variable  ...  percentage
0   Withdrawal load dip_Withdrawal load rise  ...    0.355250
1                        Withdrawal load dip  ...    0.268736
2                                   Slice.50  ...    0.044753
3                                   Slice.62  ...    0.032927
4                                   Slice.47  ...    0.031130
5                                   Slice.68  ...    0.030398
6                                   Slice.52  ...    0.024834
7                                   Slice.51  ...    0.020760
8                                   Slice.66  ...    0.017180
9                                   Slice.67  ...    0.016661
10                                  Slice.48  ...    0.016504
11                                  Slice.61  ...    0.011711
12                                  Slice.58  ...    0.011236
13                                  Slice.53  ...    0.009432
14                                  Slice.60  ...    0.008703
15                                  Slice.59  ...    0.008696
16                                     Dip.9  ...    0.007253
17                  Conv rise mm_Conv dip mm  ...    0.007243
18                                  Slice.63  ...    0.005785
19                                     Dip.6  ...    0.005678

[20 rows x 4 columns]

See the whole table with table.as_data_frame()

In [24]:
from sklearn.svm import SVR, LinearSVR
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor

In [23]:
model_path = h2o.save_model(model=glm2, path="/content/Withdraw_rise", force=True)

In [49]:
from table_evaluator import load_data, TableEvaluator
table_evaluator = TableEvaluator(sage, synthetic_data)
for col in sage.columns:
  print(table_evaluator.evaluate(target_col=col))

Correlation metric: pearsonr

Classifier F1-scores and their Jaccard similarities:
                                     f1_real  f1_fake  jaccard_similarity
index
LogisticRegression_real_testset       0.8462   0.4615              0.1818
LogisticRegression_fake_testset       0.3846   0.2308              0.1818
RandomForestClassifier_real_testset   1.0000   0.3846              0.2381
RandomForestClassifier_fake_testset   0.3077   0.3077              0.2381
DecisionTreeClassifier_real_testset   1.0000   0.5385              0.3684
DecisionTreeClassifier_fake_testset   0.3077   0.2308              0.3000
MLPClassifier_real_testset            0.8462   0.2308              0.1818
MLPClassifier_fake_testset            0.3846   0.5385              0.3684

Miscellaneous results:
                                         Result
Column Correlation Distance RMSE         0.2962
Column Correlation distance MAE          0.2197
Duplicate rows between sets (real/fake)  (0, 0)
nearest neighbor mean                    4.0784
nearest neighbor std                     0.5275

Results:
                                                Result
Basic statistics                                0.9774
Correlation column correlations                 0.7781
Mean Correlation between fake and real columns  0.9462
1 - MAPE Estimator results                      0.5864
Similarity Score                                0.8220
{'Basic statistics': 0.9774262231278188, 'Correlation column correlations': 0.778140385017866, 'Mean Correlation between fake and real columns': 0.9462021048114119, '1 - MAPE Estimator results': 0.5864073426573426, 'Similarity Score': 0.8220440139036098}

Correlation metric: pearsonr

Classifier F1-scores and their Jaccard similarities:
                                     f1_real  f1_fake  jaccard_similarity
index
LogisticRegression_real_testset       0.5385   0.0000              0.0400
LogisticRegression_fake_testset       0.0769   0.0769              0.0000
RandomForestClassifier_real_testset   0.4615   0.2308              0.1818
RandomForestClassifier_fake_testset   0.2308   0.1538              0.1818
DecisionTreeClassifier_real_testset   0.5385   0.3077              0.1818
DecisionTreeClassifier_fake_testset   0.3077   0.2308              0.0000
MLPClassifier_real_testset            0.5385   0.0769              0.1304
MLPClassifier_fake_testset            0.2308   0.0000              0.1818

Miscellaneous results:
                                         Result
Column Correlation Distance RMSE         0.2962
Column Correlation distance MAE          0.2197
Duplicate rows between sets (real/fake)  (0, 0)
nearest neighbor mean                    4.0784
nearest neighbor std                     0.5275

Results:
                                                Result
Basic statistics                                0.9774
Correlation column correlations                 0.7781
Mean Correlation between fake and real columns  0.9462
1 - MAPE Estimator results                      0.4539
Similarity Score                                0.7889
{'Basic statistics': 0.9774262231278188, 'Correlation column correlations': 0.778140385017866, 'Mean Correlation between fake and real columns': 0.9462021048114119, '1 - MAPE Estimator results': 0.45386904761904767, 'Similarity Score': 0.7889094401440362}

Correlation metric: pearsonr

Classifier F1-scores and their Jaccard similarities:
                                     f1_real  f1_fake  jaccard_similarity
index
LogisticRegression_real_testset       0.0000   0.0769              0.0000
LogisticRegression_fake_testset       0.0000   0.0769              0.0400
RandomForestClassifier_real_testset   0.0769   0.0769              0.0400
RandomForestClassifier_fake_testset   0.0000   0.0769              0.0833
DecisionTreeClassifier_real_testset   0.1538   0.3077              0.0400
DecisionTreeClassifier_fake_testset   0.0000   0.3077              0.0000
MLPClassifier_real_testset            0.0000   0.0000              0.0400
MLPClassifier_fake_testset            0.0000   0.1538              0.0000

/usr/local/lib/python3.7/dist-packages/table_evaluator/metrics.py:39: RuntimeWarning: divide by zero encountered in true_divide
  return np.mean(np.abs((y_true - y_pred) / y_true))
/usr/local/lib/python3.7/dist-packages/table_evaluator/metrics.py:39: RuntimeWarning: invalid value encountered in true_divide
  return np.mean(np.abs((y_true - y_pred) / y_true))

Miscellaneous results:
                                         Result
Column Correlation Distance RMSE         0.2962
Column Correlation distance MAE          0.2197
Duplicate rows between sets (real/fake)  (0, 0)
nearest neighbor mean                    4.0784
nearest neighbor std                     0.5275

Results:
                                                Result
Basic statistics                                0.9774
Correlation column correlations                 0.7781
Mean Correlation between fake and real columns  0.9462
1 - MAPE Estimator results                         nan
Similarity Score                                   nan
{'Basic statistics': 0.9774262231278188, 'Correlation column correlations': 0.778140385017866, 'Mean Correlation between fake and real columns': 0.9462021048114119, '1 - MAPE Estimator results': nan, 'Similarity Score': nan}

Correlation metric: pearsonr

Classifier F1-scores and their Jaccard similarities:
                                     f1_real  f1_fake  jaccard_similarity
index
LogisticRegression_real_testset       0.0000   0.0000              0.0833
LogisticRegression_fake_testset       0.0000   0.0000              0.0400
RandomForestClassifier_real_testset   0.0000   0.0000              0.0000
RandomForestClassifier_fake_testset   0.0000   0.0000              0.0000
DecisionTreeClassifier_real_testset   0.0000   0.0000              0.0000
DecisionTreeClassifier_fake_testset   0.0000   0.0000              0.0000
MLPClassifier_real_testset            0.0000   0.0000              0.0000
MLPClassifier_fake_testset            0.0000   0.0000              0.0000

/usr/local/lib/python3.7/dist-packages/table_evaluator/metrics.py:39: RuntimeWarning: invalid value encountered in true_divide
  return np.mean(np.abs((y_true - y_pred) / y_true))

Miscellaneous results:
                                         Result
Column Correlation Distance RMSE         0.2962
Column Correlation distance MAE          0.2197
Duplicate rows between sets (real/fake)  (0, 0)
nearest neighbor mean                    4.0784
nearest neighbor std                     0.5275

Results:
                                                Result
Basic statistics                                0.9774
Correlation column correlations                 0.7781
Mean Correlation between fake and real columns  0.9462
1 - MAPE Estimator results                         nan
Similarity Score                                   nan
{'Basic statistics': 0.9774262231278188, 'Correlation column correlations': 0.778140385017866, 'Mean Correlation between fake and real columns': 0.9462021048114119, '1 - MAPE Estimator results': nan, 'Similarity Score': nan}

Correlation metric: pearsonr

Classifier F1-scores and their Jaccard similarities:
                                     f1_real  f1_fake  jaccard_similarity
index
LogisticRegression_real_testset       0.0769   0.0000              0.0000
LogisticRegression_fake_testset       0.0769   0.0000              0.0000
RandomForestClassifier_real_testset   0.0000   0.0769              0.0400
RandomForestClassifier_fake_testset   0.0000   0.0000              0.0400
DecisionTreeClassifier_real_testset   0.0000   0.0000              0.0000
DecisionTreeClassifier_fake_testset   0.0000   0.0000              0.0400
MLPClassifier_real_testset            0.0769   0.0000              0.0000
MLPClassifier_fake_testset            0.0769   0.0000              0.0000

/usr/local/lib/python3.7/dist-packages/table_evaluator/metrics.py:39: RuntimeWarning: divide by zero encountered in true_divide
  return np.mean(np.abs((y_true - y_pred) / y_true))
/usr/local/lib/python3.7/dist-packages/table_evaluator/metrics.py:39: RuntimeWarning: invalid value encountered in true_divide
  return np.mean(np.abs((y_true - y_pred) / y_true))

Miscellaneous results:
                                         Result
Column Correlation Distance RMSE         0.2962
Column Correlation distance MAE          0.2197
Duplicate rows between sets (real/fake)  (0, 0)
nearest neighbor mean                    4.0784
nearest neighbor std                     0.5275

Results:
                                                Result
Basic statistics                                0.9774
Correlation column correlations                 0.7781
Mean Correlation between fake and real columns  0.9462
1 - MAPE Estimator results                         nan
Similarity Score                                   nan
{'Basic statistics': 0.9774262231278188, 'Correlation column correlations': 0.778140385017866, 'Mean Correlation between fake and real columns': 0.9462021048114119, '1 - MAPE Estimator results': nan, 'Similarity Score': nan}

Correlation metric: pearsonr

Classifier F1-scores and their Jaccard similarities:
                                     f1_real  f1_fake  jaccard_similarity
index
LogisticRegression_real_testset       0.0000   0.0769              0.0000
LogisticRegression_fake_testset       0.0000   0.0000              0.0000
RandomForestClassifier_real_testset   0.0000   0.0769              0.0000
RandomForestClassifier_fake_testset   0.0000   0.0000              0.0000
DecisionTreeClassifier_real_testset   0.0769   0.0000              0.0000
DecisionTreeClassifier_fake_testset   0.0000   0.0769              0.0000
MLPClassifier_real_testset            0.0769   0.0000              0.0000
MLPClassifier_fake_testset            0.0769   0.0000              0.0000

/usr/local/lib/python3.7/dist-packages/table_evaluator/metrics.py:39: RuntimeWarning: divide by zero encountered in true_divide
  return np.mean(np.abs((y_true - y_pred) / y_true))
/usr/local/lib/python3.7/dist-packages/table_evaluator/metrics.py:39: RuntimeWarning: invalid value encountered in true_divide
  return np.mean(np.abs((y_true - y_pred) / y_true))

Miscellaneous results:
                                         Result
Column Correlation Distance RMSE         0.2962
Column Correlation distance MAE          0.2197
Duplicate rows between sets (real/fake)  (0, 0)
nearest neighbor mean                    4.0784
nearest neighbor std                     0.5275

Results:
                                                Result
Basic statistics                                0.9774
Correlation column correlations                 0.7781
Mean Correlation between fake and real columns  0.9462
1 - MAPE Estimator results                         nan
Similarity Score                                   nan
{'Basic statistics': 0.9774262231278188, 'Correlation column correlations': 0.778140385017866, 'Mean Correlation between fake and real columns': 0.9462021048114119, '1 - MAPE Estimator results': nan, 'Similarity Score': nan}

Correlation metric: pearsonr

Classifier F1-scores and their Jaccard similarities:
                                     f1_real  f1_fake  jaccard_similarity
index
LogisticRegression_real_testset       0.0769   0.0000              0.0000
LogisticRegression_fake_testset       0.0000   0.0000              0.0000
RandomForestClassifier_real_testset   0.1538   0.0769              0.0000
RandomForestClassifier_fake_testset   0.0769   0.0000              0.0000
DecisionTreeClassifier_real_testset   0.0000   0.0000              0.0000
DecisionTreeClassifier_fake_testset   0.0000   0.0769              0.0000
MLPClassifier_real_testset            0.0769   0.0000              0.0000
MLPClassifier_fake_testset            0.0000   0.0000              0.0000

/usr/local/lib/python3.7/dist-packages/table_evaluator/metrics.py:39: RuntimeWarning: divide by zero encountered in true_divide
  return np.mean(np.abs((y_true - y_pred) / y_true))
/usr/local/lib/python3.7/dist-packages/table_evaluator/metrics.py:39: RuntimeWarning: invalid value encountered in true_divide
  return np.mean(np.abs((y_true - y_pred) / y_true))

Miscellaneous results:
                                         Result
Column Correlation Distance RMSE         0.2962
Column Correlation distance MAE          0.2197
Duplicate rows between sets (real/fake)  (0, 0)
nearest neighbor mean                    4.0784
nearest neighbor std                     0.5275

Results:
                                                Result
Basic statistics                                0.9774
Correlation column correlations                 0.7781
Mean Correlation between fake and real columns  0.9462
1 - MAPE Estimator results                         nan
Similarity Score                                   nan
{'Basic statistics': 0.9774262231278188, 'Correlation column correlations': 0.778140385017866, 'Mean Correlation between fake and real columns': 0.9462021048114119, '1 - MAPE Estimator results': nan, 'Similarity Score': nan}

Correlation metric: pearsonr

Classifier F1-scores and their Jaccard similarities:
                                     f1_real  f1_fake  jaccard_similarity
index
LogisticRegression_real_testset       0.0769   0.0000              0.0000
LogisticRegression_fake_testset       0.0000   0.0000              0.0000
RandomForestClassifier_real_testset   0.0000   0.0000              0.0400
RandomForestClassifier_fake_testset   0.0000   0.0000              0.0000
DecisionTreeClassifier_real_testset   0.0000   0.0000              0.0400
DecisionTreeClassifier_fake_testset   0.0000   0.0000              0.0400
MLPClassifier_real_testset            0.0000   0.0000              0.0000
MLPClassifier_fake_testset            0.0769   0.0000              0.0000

/usr/local/lib/python3.7/dist-packages/table_evaluator/metrics.py:39: RuntimeWarning: invalid value encountered in true_divide
  return np.mean(np.abs((y_true - y_pred) / y_true))

Miscellaneous results:
                                         Result
Column Correlation Distance RMSE         0.2962
Column Correlation distance MAE          0.2197
Duplicate rows between sets (real/fake)  (0, 0)
nearest neighbor mean                    4.0784
nearest neighbor std                     0.5275

Results:
                                                Result
Basic statistics                                0.9774
Correlation column correlations                 0.7781
Mean Correlation between fake and real columns  0.9462
1 - MAPE Estimator results                         nan
Similarity Score                                   nan
{'Basic statistics': 0.9774262231278188, 'Correlation column correlations': 0.778140385017866, 'Mean Correlation between fake and real columns': 0.9462021048114119, '1 - MAPE Estimator results': nan, 'Similarity Score': nan}

Correlation metric: pearsonr

Classifier F1-scores and their Jaccard similarities:
                                     f1_real  f1_fake  jaccard_similarity
index
LogisticRegression_real_testset       0.0769   0.0000              0.0400
LogisticRegression_fake_testset       0.0000   0.0000              0.0000
RandomForestClassifier_real_testset   0.0000   0.0000              0.0000
RandomForestClassifier_fake_testset   0.0000   0.0000              0.0000
DecisionTreeClassifier_real_testset   0.0000   0.0000              0.0000
DecisionTreeClassifier_fake_testset   0.0769   0.0769              0.0000
MLPClassifier_real_testset            0.0000   0.0000              0.0400
MLPClassifier_fake_testset            0.0000   0.0000              0.0400

/usr/local/lib/python3.7/dist-packages/table_evaluator/metrics.py:39: RuntimeWarning: invalid value encountered in true_divide
  return np.mean(np.abs((y_true - y_pred) / y_true))

Miscellaneous results:
                                         Result
Column Correlation Distance RMSE         0.2962
Column Correlation distance MAE          0.2197
Duplicate rows between sets (real/fake)  (0, 0)
nearest neighbor mean                    4.0784
nearest neighbor std                     0.5275

Results:
                                                Result
Basic statistics                                0.9774
Correlation column correlations                 0.7781
Mean Correlation between fake and real columns  0.9462
1 - MAPE Estimator results                         nan
Similarity Score                                   nan
{'Basic statistics': 0.9774262231278188, 'Correlation column correlations': 0.778140385017866, 'Mean Correlation between fake and real columns': 0.9462021048114119, '1 - MAPE Estimator results': nan, 'Similarity Score': nan}

Correlation metric: pearsonr

Classifier F1-scores and their Jaccard similarities:
                                     f1_real  f1_fake  jaccard_similarity
index
LogisticRegression_real_testset       0.0769   0.0000              0.0000
LogisticRegression_fake_testset       0.2308   0.0000              0.0400
RandomForestClassifier_real_testset   0.0000   0.0000              0.0000
RandomForestClassifier_fake_testset   0.0000   0.0000              0.0400
DecisionTreeClassifier_real_testset   0.0000   0.0000              0.0000
DecisionTreeClassifier_fake_testset   0.0000   0.0000              0.0400
MLPClassifier_real_testset            0.0000   0.0000              0.0400
MLPClassifier_fake_testset            0.0000   0.0000              0.0000

/usr/local/lib/python3.7/dist-packages/table_evaluator/metrics.py:39: RuntimeWarning: invalid value encountered in true_divide
  return np.mean(np.abs((y_true - y_pred) / y_true))

Miscellaneous results:
                                         Result
Column Correlation Distance RMSE         0.2962
Column Correlation distance MAE          0.2197
Duplicate rows between sets (real/fake)  (0, 0)
nearest neighbor mean                    4.0784
nearest neighbor std                     0.5275

Results:
                                                Result
Basic statistics                                0.9774
Correlation column correlations                 0.7781
Mean Correlation between fake and real columns  0.9462
1 - MAPE Estimator results                         nan
Similarity Score                                   nan
{'Basic statistics': 0.9774262231278188, 'Correlation column correlations': 0.778140385017866, 'Mean Correlation between fake and real columns': 0.9462021048114119, '1 - MAPE Estimator results': nan, 'Similarity Score': nan}

Correlation metric: pearsonr

Classifier F1-scores and their Jaccard similarities:
                                     f1_real  f1_fake  jaccard_similarity
index
LogisticRegression_real_testset       0.0769   0.2308              0.0400
LogisticRegression_fake_testset       0.0000   0.0000              0.0000
RandomForestClassifier_real_testset   0.0000   0.0000              0.0400
RandomForestClassifier_fake_testset   0.0000   0.0000              0.0833
DecisionTreeClassifier_real_testset   0.0769   0.0000              0.0400
DecisionTreeClassifier_fake_testset   0.0769   0.0000              0.0000
MLPClassifier_real_testset            0.0000   0.0769              0.0400
MLPClassifier_fake_testset            0.0000   0.0000              0.0833

/usr/local/lib/python3.7/dist-packages/table_evaluator/metrics.py:39: RuntimeWarning: divide by zero encountered in true_divide
  return np.mean(np.abs((y_true - y_pred) / y_true))
/usr/local/lib/python3.7/dist-packages/table_evaluator/metrics.py:39: RuntimeWarning: invalid value encountered in true_divide
  return np.mean(np.abs((y_true - y_pred) / y_true))

Miscellaneous results:
                                         Result
Column Correlation Distance RMSE         0.2962
Column Correlation distance MAE          0.2197
Duplicate rows between sets (real/fake)  (0, 0)
nearest neighbor mean                    4.0784
nearest neighbor std                     0.5275

Results:
                                                Result
Basic statistics                                0.9774
Correlation column correlations                 0.7781
Mean Correlation between fake and real columns  0.9462
1 - MAPE Estimator results                         nan
Similarity Score                                   nan
{'Basic statistics': 0.9774262231278188, 'Correlation column correlations': 0.778140385017866, 'Mean Correlation between fake and real columns': 0.9462021048114119, '1 - MAPE Estimator results': nan, 'Similarity Score': nan}

Correlation metric: pearsonr

Classifier F1-scores and their Jaccard similarities:
                                     f1_real  f1_fake  jaccard_similarity
index
LogisticRegression_real_testset       0.3077   0.0000              0.0833
LogisticRegression_fake_testset       0.0769   0.0769              0.0400
RandomForestClassifier_real_testset   0.1538   0.0000              0.0833
RandomForestClassifier_fake_testset   0.0000   0.1538              0.0000
DecisionTreeClassifier_real_testset   0.0000   0.0769              0.0400
DecisionTreeClassifier_fake_testset   0.0769   0.1538              0.0400
MLPClassifier_real_testset            0.1538   0.0000              0.0000
MLPClassifier_fake_testset            0.2308   0.0769              0.0400

/usr/local/lib/python3.7/dist-packages/table_evaluator/metrics.py:39: RuntimeWarning: divide by zero encountered in true_divide
  return np.mean(np.abs((y_true - y_pred) / y_true))

Miscellaneous results:
                                         Result
Column Correlation Distance RMSE         0.2962
Column Correlation distance MAE          0.2197
Duplicate rows between sets (real/fake)  (0, 0)
nearest neighbor mean                    4.0784
nearest neighbor std                     0.5275

Results:
                                                Result
Basic statistics                                0.9774
Correlation column correlations                 0.7781
Mean Correlation between fake and real columns  0.9462
1 - MAPE Estimator results                        -inf
Similarity Score                                  -inf
{'Basic statistics': 0.9774262231278188, 'Correlation column correlations': 0.778140385017866, 'Mean Correlation between fake and real columns': 0.9462021048114119, '1 - MAPE Estimator results': -inf, 'Similarity Score': -inf}

Correlation metric: pearsonr

Classifier F1-scores and their Jaccard similarities:
                                     f1_real  f1_fake  jaccard_similarity
index
LogisticRegression_real_testset       0.1538   0.0000              0.0833
LogisticRegression_fake_testset       0.0769   0.0000              0.0400
RandomForestClassifier_real_testset   0.2308   0.1538              0.1304
RandomForestClassifier_fake_testset   0.0769   0.0769              0.0000
DecisionTreeClassifier_real_testset   0.1538   0.0000              0.0833
DecisionTreeClassifier_fake_testset   0.1538   0.0769              0.0000
MLPClassifier_real_testset            0.0000   0.0769              0.0400
MLPClassifier_fake_testset            0.0769   0.0000              0.0400

/usr/local/lib/python3.7/dist-packages/table_evaluator/metrics.py:39: RuntimeWarning: divide by zero encountered in true_divide
  return np.mean(np.abs((y_true - y_pred) / y_true))

Miscellaneous results:
                                         Result
Column Correlation Distance RMSE         0.2962
Column Correlation distance MAE          0.2197
Duplicate rows between sets (real/fake)  (0, 0)
nearest neighbor mean                    4.0784
nearest neighbor std                     0.5275

Results:
                                                Result
Basic statistics                                0.9774
Correlation column correlations                 0.7781
Mean Correlation between fake and real columns  0.9462
1 - MAPE Estimator results                        -inf
Similarity Score                                  -inf
{'Basic statistics': 0.9774262231278188, 'Correlation column correlations': 0.778140385017866, 'Mean Correlation between fake and real columns': 0.9462021048114119, '1 - MAPE Estimator results': -inf, 'Similarity Score': -inf}

Correlation metric: pearsonr

Classifier F1-scores and their Jaccard similarities:
                                     f1_real  f1_fake  jaccard_similarity
index
LogisticRegression_real_testset       0.0000   0.0000              0.0000
LogisticRegression_fake_testset       0.1538   0.0000              0.0000
RandomForestClassifier_real_testset   0.0000   0.0000              0.0000
RandomForestClassifier_fake_testset   0.0000   0.0769              0.0000
DecisionTreeClassifier_real_testset   0.0000   0.0769              0.0400
DecisionTreeClassifier_fake_testset   0.0000   0.0000              0.0000
MLPClassifier_real_testset            0.0000   0.0000              0.0833
MLPClassifier_fake_testset            0.0000   0.0000              0.0400

/usr/local/lib/python3.7/dist-packages/table_evaluator/metrics.py:39: RuntimeWarning: divide by zero encountered in true_divide
  return np.mean(np.abs((y_true - y_pred) / y_true))
/usr/local/lib/python3.7/dist-packages/table_evaluator/metrics.py:39: RuntimeWarning: invalid value encountered in true_divide
  return np.mean(np.abs((y_true - y_pred) / y_true))

Miscellaneous results:
                                         Result
Column Correlation Distance RMSE         0.2962
Column Correlation distance MAE          0.2197
Duplicate rows between sets (real/fake)  (0, 0)
nearest neighbor mean                    4.0784
nearest neighbor std                     0.5275

Results:
                                                Result
Basic statistics                                0.9774
Correlation column correlations                 0.7781
Mean Correlation between fake and real columns  0.9462
1 - MAPE Estimator results                         nan
Similarity Score                                   nan
{'Basic statistics': 0.9774262231278188, 'Correlation column correlations': 0.778140385017866, 'Mean Correlation between fake and real columns': 0.9462021048114119, '1 - MAPE Estimator results': nan, 'Similarity Score': nan}

Correlation metric: pearsonr

Classifier F1-scores and their Jaccard similarities:
                                     f1_real  f1_fake  jaccard_similarity
index
LogisticRegression_real_testset       0.0000   0.1538              0.0000
LogisticRegression_fake_testset       0.0000   0.0000              0.0000
RandomForestClassifier_real_testset   0.0000   0.1538              0.0000
RandomForestClassifier_fake_testset   0.0000   0.0000              0.0000
DecisionTreeClassifier_real_testset   0.0000   0.0769              0.0000
DecisionTreeClassifier_fake_testset   0.0000   0.0000              0.0000
MLPClassifier_real_testset            0.0000   0.2308              0.0000
MLPClassifier_fake_testset            0.0000   0.0000              0.0000

/usr/local/lib/python3.7/dist-packages/table_evaluator/metrics.py:39: RuntimeWarning: divide by zero encountered in true_divide
  return np.mean(np.abs((y_true - y_pred) / y_true))
/usr/local/lib/python3.7/dist-packages/table_evaluator/metrics.py:39: RuntimeWarning: invalid value encountered in true_divide
  return np.mean(np.abs((y_true - y_pred) / y_true))

Miscellaneous results:
                                         Result
Column Correlation Distance RMSE         0.2962
Column Correlation distance MAE          0.2197
Duplicate rows between sets (real/fake)  (0, 0)
nearest neighbor mean                    4.0784
nearest neighbor std                     0.5275

Results:
                                                Result
Basic statistics                                0.9774
Correlation column correlations                 0.7781
Mean Correlation between fake and real columns  0.9462
1 - MAPE Estimator results                         nan
Similarity Score                                   nan
{'Basic statistics': 0.9774262231278188, 'Correlation column correlations': 0.778140385017866, 'Mean Correlation between fake and real columns': 0.9462021048114119, '1 - MAPE Estimator results': nan, 'Similarity Score': nan}

Correlation metric: pearsonr

Classifier F1-scores and their Jaccard similarities:
                                     f1_real  f1_fake  jaccard_similarity
index
LogisticRegression_real_testset       0.3846   0.1538              0.1818
LogisticRegression_fake_testset       0.0769   0.0000              0.0000
RandomForestClassifier_real_testset   0.6154   0.1538              0.0400
RandomForestClassifier_fake_testset   0.0000   0.0769              0.0400
DecisionTreeClassifier_real_testset   0.6154   0.0769              0.1304
DecisionTreeClassifier_fake_testset   0.0000   0.0000              0.0000
MLPClassifier_real_testset            0.6154   0.0769              0.0000
MLPClassifier_fake_testset            0.0769   0.0000              0.0000

/usr/local/lib/python3.7/dist-packages/table_evaluator/metrics.py:39: RuntimeWarning: divide by zero encountered in true_divide
  return np.mean(np.abs((y_true - y_pred) / y_true))
/usr/local/lib/python3.7/dist-packages/table_evaluator/metrics.py:39: RuntimeWarning: invalid value encountered in true_divide
  return np.mean(np.abs((y_true - y_pred) / y_true))

Miscellaneous results:
                                         Result
Column Correlation Distance RMSE         0.2962
Column Correlation distance MAE          0.2197
Duplicate rows between sets (real/fake)  (0, 0)
nearest neighbor mean                    4.0784
nearest neighbor std                     0.5275

Results:
                                                Result
Basic statistics                                0.9774
Correlation column correlations                 0.7781
Mean Correlation between fake and real columns  0.9462
1 - MAPE Estimator results                         nan
Similarity Score                                   nan
{'Basic statistics': 0.9774262231278188, 'Correlation column correlations': 0.778140385017866, 'Mean Correlation between fake and real columns': 0.9462021048114119, '1 - MAPE Estimator results': nan, 'Similarity Score': nan}

Correlation metric: pearsonr

Classifier F1-scores and their Jaccard similarities:
                                     f1_real  f1_fake  jaccard_similarity
index
LogisticRegression_real_testset       0.8462   0.6923              0.3684
LogisticRegression_fake_testset       0.6923   0.5385              0.5294
RandomForestClassifier_real_testset   0.9231   0.6923              0.6250
RandomForestClassifier_fake_testset   0.7692   0.6923              0.8571
DecisionTreeClassifier_real_testset   1.0000   0.7692              0.6250
DecisionTreeClassifier_fake_testset   0.5385   0.5385              0.7333
MLPClassifier_real_testset            0.7692   0.6923              0.8571
MLPClassifier_fake_testset            0.6154   0.6923              0.8571

Miscellaneous results:
                                         Result
Column Correlation Distance RMSE         0.2962
Column Correlation distance MAE          0.2197
Duplicate rows between sets (real/fake)  (0, 0)
nearest neighbor mean                    4.0784
nearest neighbor std                     0.5275

Results:
                                                Result
Basic statistics                                0.9774
Correlation column correlations                 0.7781
Mean Correlation between fake and real columns  0.9462
1 - MAPE Estimator results                      0.8488
Similarity Score                                0.8876
{'Basic statistics': 0.9774262231278188, 'Correlation column correlations': 0.778140385017866, 'Mean Correlation between fake and real columns': 0.9462021048114119, '1 - MAPE Estimator results': 0.8487737956487956, 'Similarity Score': 0.8876356271514731}

Correlation metric: pearsonr

Classifier F1-scores and their Jaccard similarities:
                                     f1_real  f1_fake  jaccard_similarity
index
LogisticRegression_real_testset       0.7692   0.6923              0.6250
LogisticRegression_fake_testset       0.6154   0.5385              0.3000
RandomForestClassifier_real_testset   0.8462   0.5385              0.5294
RandomForestClassifier_fake_testset   0.3846   0.4615              0.4444
DecisionTreeClassifier_real_testset   1.0000   0.6923              0.5294
DecisionTreeClassifier_fake_testset   0.4615   0.5385              0.3000
MLPClassifier_real_testset            1.0000   0.4615              0.3000
MLPClassifier_fake_testset            0.5385   0.2308              0.2381

Miscellaneous results:
                                         Result
Column Correlation Distance RMSE         0.2962
Column Correlation distance MAE          0.2197
Duplicate rows between sets (real/fake)  (0, 0)
nearest neighbor mean                    4.0784
nearest neighbor std                     0.5275

Results:
                                                Result
Basic statistics                                0.9774
Correlation column correlations                 0.7781
Mean Correlation between fake and real columns  0.9462
1 - MAPE Estimator results                      0.7034
Similarity Score                                0.8513
{'Basic statistics': 0.9774262231278188, 'Correlation column correlations': 0.778140385017866, 'Mean Correlation between fake and real columns': 0.9462021048114119, '1 - MAPE Estimator results': 0.703389319014319, 'Similarity Score': 0.851289507992854}

In [30]:
from h2o.estimators.glm import H2OGeneralizedLinearEstimator
train_, valid = train.split_frame(ratios = [.85])
for cols in ['Dip', 'Slice', 'Block', 'SAGES']:
  train_[cols] = train_[cols].asfactor()
  valid[cols] = valid[cols].asfactor()
interaction_pairs = [("Dip load", "Rise load"),
                    ("Withdrawal load dip", "Withdrawal load rise"),
                     ("Conv rise mm", "Conv dip mm"),
                      ('Dip load', 'Rise load')]

glm3 = H2OGeneralizedLinearEstimator(nfolds=5,
                                    alpha=0,
                                    interaction_pairs=interaction_pairs,
                                    keep_cross_validation_models=True,
                                    stopping_metric='rmse',
                                    family='poisson',
                                    seed=12
                                    )

X = train_.drop(['Withdrawal load dip'], axis=1)

glm3.train(x = X.columns, y = 'Withdrawal load dip', training_frame = train_, validation_frame = valid)

print(glm3)

/usr/local/lib/python3.7/dist-packages/h2o/estimators/estimator_base.py:200: RuntimeWarning: Stopping metric is ignored for _stopping_rounds=0.
  warnings.warn(mesg["message"], RuntimeWarning)

glm Model Build progress: |███████████████████████████████████████████████| 100%
Model Details
=============
H2OGeneralizedLinearEstimator :  Generalized Linear Modeling
Model Key:  GLM_model_python_1623533504698_9


GLM Model: summary

      family  ... number_of_iterations  training_frame
0    poisson  ...                    4  py_96_sid_8c15

[1 rows x 8 columns]

ModelMetricsRegressionGLM: glm
** Reported on train data. **

MSE: 119.70461301107402
RMSE: 10.94096033312771
MAE: 8.000912629661133
RMSLE: 0.1015482861168423
R^2: 0.9187826215196108
Mean Residual Deviance: 0.9713648180765219
Null degrees of freedom: 851
Residual degrees of freedom: 801
Null deviance: 9789.060884828421
Residual deviance: 827.6028250011966
AIC: 6651.68384249046

ModelMetricsRegressionGLM: glm
** Reported on validation data. **

MSE: 100.1257244082575
RMSE: 10.006284245825595
MAE: 7.271668409285983
RMSLE: 0.11572076456620867
R^2: 0.9228438952522819
Mean Residual Deviance: 1.0363985795022919
Null degrees of freedom: 147
Residual degrees of freedom: 97
Null deviance: 1547.0542577302697
Residual deviance: 153.38698976633918
AIC: 1248.3461085456279

ModelMetricsRegressionGLM: glm
** Reported on cross-validation data. **

MSE: 136.42015446532272
RMSE: 11.679903872263791
MAE: 8.479812688473055
RMSLE: 0.10599359373721452
R^2: 0.9074414340528524
Mean Residual Deviance: 1.079948859185594
Null degrees of freedom: 851
Residual degrees of freedom: 801
Null deviance: 9817.06291061256
Residual deviance: 920.116428026126
AIC: 6744.1974455153895

Cross-Validation Metrics Summary:

                                 mean  ...  cv_4_valid  cv_5_valid
0                     mae    8.485912  ...    8.330692     8.97016
1  mean_residual_deviance   1.0824308  ...     1.00817   1.2869754
2                     mse    136.5304  ...   150.23024   145.82587
3           null_deviance   1963.4126  ...   1679.1051   1964.2445
4                      r2   0.9055573  ...   0.8815303   0.8988636
5       residual_deviance   184.02328  ...   176.42975   213.63791
6                    rmse   11.666391  ...  12.2568445   12.075838
7                   rmsle  0.10573017  ...  0.09405697  0.12109421

[8 rows x 8 columns]

Scoring History:

               timestamp  ... validation_mae  validation_r2
0    2021-06-12 21:48:05  ...
1    2021-06-12 21:48:05  ...
2    2021-06-12 21:48:05  ...
3    2021-06-12 21:48:05  ...
4    2021-06-12 21:48:05  ...        7.27167       0.922844

[5 rows x 14 columns]

Variable Importances:

                                    variable  ...  percentage
0   Withdrawal load dip_Withdrawal load rise  ...    0.383626
1                       Withdrawal load rise  ...    0.269944
2                                   Slice.50  ...    0.043982
3                                   Slice.62  ...    0.034629
4                                   Slice.61  ...    0.025110
5                                   Slice.63  ...    0.024050
6                                   Slice.48  ...    0.023578
7                                   Slice.68  ...    0.019263
8                                   Slice.64  ...    0.018637
9                                   Slice.66  ...    0.013891
10                                  Slice.58  ...    0.011962
11                                  Slice.47  ...    0.010988
12                                  Slice.54  ...    0.010650
13                                  Slice.46  ...    0.009123
14                                  Slice.53  ...    0.009073
15                                  Slice.52  ...    0.007661
16                                  Slice.49  ...    0.007505
17                                  Slice.51  ...    0.007055
18                                  Slice.67  ...    0.006979
19                                    Dip.11  ...    0.004839

[20 rows x 4 columns]

See the whole table with table.as_data_frame()

In [31]:
model_path = h2o.save_model(model=glm3, path="/content/Withdraw_dip", force=True)